Fix progress timing for `PutObject_Test9 ` test (fixes #1078)
minio/minio-dotnet pull request #1079
Opened 2024-05-18 10:57 UTC by ramondeklein

Fixes timing issue when running progress test.

2024-05-18 11:06 UTC, harshavardhana submitted a review, later dismissed

2024-05-19 01:08 UTC, ebozduman requested changes
There are 3 more instances of old `new Progress(<ProgressReport>(...` that need to be replaced with `new SyncProgress(<ProgressReport>(...`
in 3 files:
- API.md
- Program.cs (Functional)
- FunctionalTest.cs

2024-05-19 09:49 UTC, ramondeklein commented
@ebozduman I've fixed the occurences in most places, but I didn't replace the implementation in the API description. I did describe the implications of `Progress<T>` and when to use `SyncProgress<T>`. But using `SyncProgress<T>` isn't always recommended and it may result in other issue.

2024-05-19 16:00 UTC, harshavardhana approved these changes

2024-05-19 16:00 UTC, merged