using interface IReadOnlyDictionary instead of a dicrionary in TagSet and Tagging
minio/minio-dotnet pull request #1149
Opened 2024-08-02 12:54 UTC by danilenko-a

Interface limitation: The dictionary with tags is only needed for enumeration.

2024-08-21 11:34 UTC, ebozduman requested changes
There are 2 more occurrences of the same IDictionary structure.

Minio/DataModel/
           |==>           ILM/AndOperator.cs at line#45 (on master branch)
           |==>           Replication/AndOperator.cs at line#53 (on master branch)

2024-09-02 04:03 UTC, danilenko-a commented
Pull request updated

2024-09-02 08:32 UTC, ebozduman commented
That's great @danilenko-a!
Could you also add some **`functional test(s)`** for this PR/change?
Maybe, you can do the testing simply by adding some assertions or checks in existing functional tests about **`Tags`**, **`ILM`** and **`Replication`** where **`IReadOnlyDictionary`** is introduced.
Please make sure the tests/checks are created for **`.../minio-dotnet/Mino.Functional.Tests`**.

2025-01-05 03:08 UTC, danilenko-a commented
If the current assertions test the operation of the IDictionary and the Dictionary, then they are true for the IReadOnlyDictionary, since this is a relaxation of the requirements for the input data.

2025-01-05 03:10 UTC, danilenko-a commented
However, I apologize because I don't understand what functional tests are. I only understand unit tests.

2026-03-02 16:07 UTC, harshavardhana commented
Thank you for your contribution! This repository recently went through a significant architectural overhaul (see #1363 — fully rewritten .NET Core based SDK). As a result, the codebase structure has changed substantially and this PR is no longer applicable in its current form. We are closing it as part of this cleanup. If you'd still like to contribute this functionality, please open a new PR against the updated codebase.

2026-03-02 16:07 UTC, closed without merging