LegalHold APIs (Set, Get) with Args, Response.
minio/minio-dotnet pull request #495
Opened 2020-12-01 22:53 UTC by BigUstad

Functional Test, Examples

2020-12-05 00:25 UTC, kannappanr approved these changes
LGTM

2020-12-05 01:49 UTC, poornas requested changes

2020-12-05 01:49 UTC, poornas commented on Minio/ApiEndpoints/IObjectOperations.cs
> +        /// <exception cref="InvalidObjectNameException">When bucketName is invalid</exception>
```suggestion
        /// <exception cref="InvalidObjectNameException">When objectName is invalid</exception>
```

2020-12-05 01:49 UTC, poornas commented on Minio/ApiEndpoints/IObjectOperations.cs
> +        /// <exception cref="InvalidObjectNameException">When bucketName is invalid</exception>
```suggestion
        /// <exception cref="InvalidObjectNameException">When objectName is invalid</exception>
```

2020-12-05 01:49 UTC, poornas commented on Minio/ApiEndpoints/ObjectOperations.cs
> +        /// <exception cref="InvalidObjectNameException">When bucketName is invalid</exception>
```suggestion
        /// <exception cref="InvalidObjectNameException">When objectName is invalid</exception>
```

2020-12-07 23:17 UTC, BigUstad commented on Minio/ApiEndpoints/IObjectOperations.cs
> +        /// <exception cref="InvalidObjectNameException">When bucketName is invalid</exception>
It is corrected. Thx. PTAL.

2020-12-10 17:42 UTC, BigUstad commented on Minio/ApiEndpoints/ObjectOperations.cs
> +        /// <exception cref="InvalidObjectNameException">When bucketName is invalid</exception>
Changed. PTAL.

2020-12-10 17:42 UTC, BigUstad commented on Minio/ApiEndpoints/IObjectOperations.cs
> +        /// <exception cref="InvalidObjectNameException">When bucketName is invalid</exception>
Changed. PTAL.

2020-12-12 19:56 UTC, kannappanr commented
@poornas PTAL

2020-12-13 04:16 UTC, poornas approved these changes
LGTM

2020-12-13 04:16 UTC, poornas commented on Minio/ApiEndpoints/IObjectOperations.cs
> +        /// Get the configuration object for Legal Hold Status
```suggestion
        /// Set the configuration object for Legal Hold Status

2020-12-13 04:26 UTC, BigUstad commented on Minio/ApiEndpoints/IObjectOperations.cs
> +        /// Get the configuration object for Legal Hold Status
Changed it. Tx.

2020-12-16 02:03 UTC, kannappanr commented on Minio/Exceptions/MissingObjectLockConfiguration.cs
> + * MinIO .NET Library for Amazon S3 Compatible Cloud Storage, (C) 2017 MinIO, Inc.
```suggestion
 * MinIO .NET Library for Amazon S3 Compatible Cloud Storage, (C) 2020 MinIO, Inc.
```

2020-12-17 06:09 UTC, kannappanr approved these changes

2020-12-17 18:01 UTC, merged