Object Tags APIs - Set, Get, Remove.
minio/minio-dotnet pull request #503
Opened 2020-12-10 08:16 UTC by BigUstad

Example, Functional test.

2020-12-14 04:05 UTC, kannappanr commented on Minio/DataModel/Tagging.cs
> +                // ns.Add("", "http://s3.amazonaws.com/doc/2006-03-01/");
```suggestion
```

2020-12-14 04:09 UTC, kannappanr commented on Minio/DataModel/Tagging.cs
> +                //xs.Serialize(xw, this);
```suggestion
```

2020-12-14 04:09 UTC, kannappanr commented on Minio/DataModel/Tagging.cs
> +                //xs.Serialize(xw, this, ns);
```suggestion
```

2020-12-14 17:15 UTC, sinhaashish requested changes
please check the new line in all the edited files

2020-12-15 01:12 UTC, BigUstad commented
> please check the new line in all the edited files

The newline at the end of the file is not enforced as per C# compiler rules. I've tried to not have newline at the end of the file in minio-dotnet as I observed it in files before.

2020-12-15 01:18 UTC, BigUstad commented on Minio/DataModel/Tagging.cs
> +                // ns.Add("", "http://s3.amazonaws.com/doc/2006-03-01/");
Removed.

2020-12-15 07:04 UTC, BigUstad commented on Minio.Examples/Cases/GetObjectTags.cs
> +                    Console.WriteLine($"Got Object Tags set for bucket {bucketName}/{objectName}.");
Change made..PTAL.

2020-12-15 07:05 UTC, BigUstad commented on Minio.Examples/Cases/GetObjectTags.cs
> +}
Plz refer https://github.com/minio/minio-dotnet/pull/503#issuecomment-744943647

2020-12-15 07:05 UTC, BigUstad commented on Minio.Examples/Cases/RemoveBucketTags.cs
> +        // Put Encryption Configuration for the bucket
Change made. PTAL.

2020-12-15 07:05 UTC, BigUstad commented on Minio.Examples/Cases/RemoveObjectTags.cs
> +        // Put Encryption Configuration for the bucket
Changed.

2020-12-15 07:05 UTC, BigUstad commented on Minio.Examples/Cases/SetObjectTags.cs
> +        // Put Encryption Configuration for the bucket
Changed/Updated.

2020-12-15 16:37 UTC, sinhaashish approved these changes

2020-12-18 07:43 UTC, kannappanr commented on Minio.Examples/Cases/RemoveObjectTags.cs
> +        // Remove Tags set for the bucket
```suggestion
```

2020-12-18 09:20 UTC, BigUstad commented on Minio.Examples/Cases/RemoveObjectTags.cs
> +        // Remove Tags set for the bucket
Comment updated

2020-12-21 21:50 UTC, kannappanr approved these changes
LGTM

2020-12-21 21:50 UTC, merged