Func tests adding gateway, NotImplemented Exception handling
minio/minio-dotnet pull request #535
Opened 2021-04-27 16:18 UTC by BigUstad

Also extending TearDown function

Signed-off-by: Priyank Raj <priyank.raj@gatech.edu>

2021-04-29 16:23 UTC, ebozduman commented
@Priyank,

Could you look into build failures?

2021-04-29 18:29 UTC, BigUstad commented
> @priyank,
> 
> Could you look into build failures?

They aren't build failures. They're encountered because of Play's "Please reduce your request" error. I'll give it another run and see if it is resolved.

2021-04-30 06:19 UTC, BigUstad commented
> @priyank,
> 
> Could you look into build failures?

@ebozduman PTAL

2021-05-05 12:47 UTC, ebozduman commented
Functional test run fails for the following s3 gateway setup:
1. Run standalone minio server
    `minio server --address :9001 /tmp/mm1/`
2. Run s3 gateway with your endpoint set to standalone minio server
    `AWS_ACCESS_KEY=minio AWS_SECRET_KEY=minio123 minio gateway s3 http://172.17.0.1:9001`
3. Run the Functional test after setting up the env vars
    `dotnet build; dotnet run --project ./Minio.Functional.Tests/Minio.Functional.Tests.csproj`

Here is the error message and the stack trace:
```
:
:
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.28
ListenBucketNotificationsAsync received: <?xml version="1.0" encoding="UTF-8"?>
ListenBucketNotificationsAsync received: <Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><BucketName>miniodotnetr4l0clnmmb13ges</BucketName><Resource>/miniodotnetr4l0clnmmb13ges/</Resource><RequestId>167C2B896BD271D8</RequestId><HostId>d0b773ce-ab7d-4d2b-8a03-3d68204a6c26</HostId></Error>
OnError: Object reference not set to an instance of an object.
{"name":"minio-dotnet : ListenBucketNotificationsAsync_Test1","function":"IObservable<MinioNotificationRaw> ListenBucketNotificationsAsync(ListenBucketNotificationsArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnetr4l0clnmmb13ges","objectName":"miniodotnetg6vcd7ag1v","contentType":"application/octet-stream","size":"1MB"},"duration":622,"status":"NA","alert":"A header you provided implies functionality that is not implemented","message":"System.NotImplementedException: A header you provided implies functionality that is not implemented\n   at Minio.Functional.Tests.FunctionalTest.ListenBucketNotificationsAsync_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 4081"}

Unhandled Exception: System.AggregateException: One or more errors occurred. (A header you provided implies functionality that is not implemented) ---> System.NotImplementedException: A header you provided implies functionality that is not implemented
   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 763
   at Minio.MinioClient.ParseError(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 606
   at Minio.MinioClient.<>c.<.ctor>b__166_0(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 84
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 813
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 580
   at Minio.MinioClient.GetVersioningAsync(GetVersioningArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 122
   at Minio.Functional.Tests.FunctionalTest.TearDown(MinioClient minio, String bucketName) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 523
   at Minio.Functional.Tests.FunctionalTest.ListenBucketNotificationsAsync_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 4107
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 90
```

2021-05-05 12:49 UTC, ebozduman requested changes
Please check the failure and let me know if you want to know more details.

2021-05-05 16:28 UTC, BigUstad commented
> Functional test run fails for the following s3 gateway setup:
> 
> 1. Run standalone minio server
>    `minio server --address :9001 /tmp/mm1/`
> 2. Run s3 gateway with your endpoint set to standalone minio server
>    `AWS_ACCESS_KEY=minio AWS_SECRET_KEY=minio123 minio gateway s3 http://172.17.0.1:9001`
> 3. Run the Functional test after setting up the env vars
>    `dotnet build; dotnet run --project ./Minio.Functional.Tests/Minio.Functional.Tests.csproj`
> 
> Here is the error message and the stack trace:
> 
> ```
> :
> :
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:02.28
> ListenBucketNotificationsAsync received: <?xml version="1.0" encoding="UTF-8"?>
> ListenBucketNotificationsAsync received: <Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><BucketName>miniodotnetr4l0clnmmb13ges</BucketName><Resource>/miniodotnetr4l0clnmmb13ges/</Resource><RequestId>167C2B896BD271D8</RequestId><HostId>d0b773ce-ab7d-4d2b-8a03-3d68204a6c26</HostId></Error>
> OnError: Object reference not set to an instance of an object.
> {"name":"minio-dotnet : ListenBucketNotificationsAsync_Test1","function":"IObservable<MinioNotificationRaw> ListenBucketNotificationsAsync(ListenBucketNotificationsArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnetr4l0clnmmb13ges","objectName":"miniodotnetg6vcd7ag1v","contentType":"application/octet-stream","size":"1MB"},"duration":622,"status":"NA","alert":"A header you provided implies functionality that is not implemented","message":"System.NotImplementedException: A header you provided implies functionality that is not implemented\n   at Minio.Functional.Tests.FunctionalTest.ListenBucketNotificationsAsync_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 4081"}
> 
> Unhandled Exception: System.AggregateException: One or more errors occurred. (A header you provided implies functionality that is not implemented) ---> System.NotImplementedException: A header you provided implies functionality that is not implemented
>    at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 763
>    at Minio.MinioClient.ParseError(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 606
>    at Minio.MinioClient.<>c.<.ctor>b__166_0(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 84
>    at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 813
>    at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 580
>    at Minio.MinioClient.GetVersioningAsync(GetVersioningArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 122
>    at Minio.Functional.Tests.FunctionalTest.TearDown(MinioClient minio, String bucketName) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 523
>    at Minio.Functional.Tests.FunctionalTest.ListenBucketNotificationsAsync_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 4107
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 90
> ```

NotImplemented Exception is to be expected, but it shouldn't stop the test run. I'll look into it.

2021-05-05 19:26 UTC, BigUstad commented
> Please check the failure and let me know if you want to know more details.

@ebozduman PTAL

2021-05-07 09:42 UTC, ebozduman commented
@BigUstad,

I ran functional tests again on an s3 gateway, but this time I had an EC minio behind the gateway.

Here is the run log with the error message:
```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.94
ListenBucketNotificationsAsync received: {"Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2021-05-07T09:23:16.343Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"principalId":"Q3AM3UQ867SPQQA43P2F"},"requestParameters":{"principalId":"Q3AM3UQ867SPQQA43P2F","region":"","sourceIPAddress":"73.63.176.167"},"responseElements":{"content-length":"0","x-amz-request-id":"167CBE79CDD27EF0","x-minio-deployment-id":"423bb0de-e407-4e5c-b830-27b61fa31242","x-minio-origin-endpoint":"https://147.75.201.93:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"miniodotnet6jbso00k4qs5vfk","ownerIdentity":{"principalId":"Q3AM3UQ867SPQQA43P2F"},"arn":"arn:aws:s3:::miniodotnet6jbso00k4qs5vfk"},"object":{"key":"miniodotnetnbgjbd9jld","size":1024,"eTag":"9fac5d8be9497941e72b25af128474af","contentType":"application/octet-stream","userMetadata":{"content-type":"application/octet-stream"},"sequencer":"167CBE79D06A7D26"}},"source":{"host":"73.63.176.167","port":"","userAgent":"MinIO (Linux 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021;X64) minio-dotnet/1.0.9"}}]}
{"name":"minio-dotnet : ListenBucketNotificationsAsync_Test1","function":"IObservable<MinioNotificationRaw> ListenBucketNotificationsAsync(ListenBucketNotificationsArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnet6jbso00k4qs5vfk","objectName":"miniodotnetnbgjbd9jld","contentType":"application/octet-stream","size":"1MB"},"duration":2332,"status":"PASS"}
{"name":"minio-dotnet : BucketExists_Test","function":"Task<bool> BucketExistsAsync(string bucketName, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnet0cagg"},"duration":501,"status":"PASS"}
{"name":"minio-dotnet : MakeBucket_Test1","function":"Task MakeBucketAsync(string bucketName, string location = 'us-east-1', CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotneta1q5w3nb28ukjq5gaxgxx0pfn1ebbqfufy9mkbm7qxgdihfu3b","region":"us-east-1"},"duration":190,"status":"FAIL","alert":"MinIO API responded with message=Please reduce your request","message":"Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=Please reduce your request\n   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 779\n   at Minio.MinioClient.ParseError(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 606\n   at Minio.MinioClient.<>c.<.ctor>b__166_0(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 84\n   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 813\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 580\n   at Minio.MinioClient.MakeBucketAsync(MakeBucketArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 107\n   at Minio.Functional.Tests.FunctionalTest.MakeBucket_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 249"}

Unhandled Exception: System.AggregateException: One or more errors occurred. (MinIO API responded with message=Please reduce your request) ---> Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=Please reduce your request
   at Minio.Functional.Tests.FunctionalTest.MakeBucket_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 257
   at Minio.Functional.Tests.FunctionalTest.MakeBucket_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 262
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 96
```

I also remember at some point, we talked about not stopping the test run when a major issue happens, but keep continue to run the rest of the tests to give each test a chance to run. This way, we can collect a complete test results/failures.

2021-05-07 16:13 UTC, BigUstad commented
> @BigUstad,
> 
> I ran functional tests again on an s3 gateway, but this time I had an EC minio behind the gateway.
> 
> Here is the run log with the error message:
> 
> ```
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:03.94
> ListenBucketNotificationsAsync received: {"Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2021-05-07T09:23:16.343Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"principalId":"Q3AM3UQ867SPQQA43P2F"},"requestParameters":{"principalId":"Q3AM3UQ867SPQQA43P2F","region":"","sourceIPAddress":"73.63.176.167"},"responseElements":{"content-length":"0","x-amz-request-id":"167CBE79CDD27EF0","x-minio-deployment-id":"423bb0de-e407-4e5c-b830-27b61fa31242","x-minio-origin-endpoint":"https://147.75.201.93:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"miniodotnet6jbso00k4qs5vfk","ownerIdentity":{"principalId":"Q3AM3UQ867SPQQA43P2F"},"arn":"arn:aws:s3:::miniodotnet6jbso00k4qs5vfk"},"object":{"key":"miniodotnetnbgjbd9jld","size":1024,"eTag":"9fac5d8be9497941e72b25af128474af","contentType":"application/octet-stream","userMetadata":{"content-type":"application/octet-stream"},"sequencer":"167CBE79D06A7D26"}},"source":{"host":"73.63.176.167","port":"","userAgent":"MinIO (Linux 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021;X64) minio-dotnet/1.0.9"}}]}
> {"name":"minio-dotnet : ListenBucketNotificationsAsync_Test1","function":"IObservable<MinioNotificationRaw> ListenBucketNotificationsAsync(ListenBucketNotificationsArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnet6jbso00k4qs5vfk","objectName":"miniodotnetnbgjbd9jld","contentType":"application/octet-stream","size":"1MB"},"duration":2332,"status":"PASS"}
> {"name":"minio-dotnet : BucketExists_Test","function":"Task<bool> BucketExistsAsync(string bucketName, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnet0cagg"},"duration":501,"status":"PASS"}
> {"name":"minio-dotnet : MakeBucket_Test1","function":"Task MakeBucketAsync(string bucketName, string location = 'us-east-1', CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotneta1q5w3nb28ukjq5gaxgxx0pfn1ebbqfufy9mkbm7qxgdihfu3b","region":"us-east-1"},"duration":190,"status":"FAIL","alert":"MinIO API responded with message=Please reduce your request","message":"Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=Please reduce your request\n   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 779\n   at Minio.MinioClient.ParseError(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 606\n   at Minio.MinioClient.<>c.<.ctor>b__166_0(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 84\n   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 813\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 580\n   at Minio.MinioClient.MakeBucketAsync(MakeBucketArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 107\n   at Minio.Functional.Tests.FunctionalTest.MakeBucket_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 249"}
> 
> Unhandled Exception: System.AggregateException: One or more errors occurred. (MinIO API responded with message=Please reduce your request) ---> Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=Please reduce your request
>    at Minio.Functional.Tests.FunctionalTest.MakeBucket_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 257
>    at Minio.Functional.Tests.FunctionalTest.MakeBucket_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 262
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()
>    at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 96
> ```
> 
> I also remember at some point, we talked about not stopping the test run when a major issue happens, but keep continue to run the rest of the tests to give each test a chance to run. This way, we can collect a complete test results/failures.

In a recent discussion, it was put forth that the decision is to stop running the tests when an exception is thrown (unless it is something like 'NotImplemented' etc) so that we/user fixes the issue before running the tests again. 
There is no getting around  the "Please reduce your request" error.

2021-05-10 11:08 UTC, ebozduman commented
Priyank,

The following usual time-out error I hit during GCS testings shows that we did not capture it and failed without graceful cleanup.
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (MinIO API responded with message=Connection error: The operation has timed out.. Status code=0, response=The operation has timed out., content=) ---> Minio.Exceptions.ConnectionException: MinIO API responded with message=Connection error: The operation has timed out.. Status code=0, response=The operation has timed out., content=
   at Minio.MinioClient.ParseErrorNoContent(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 623
   at Minio.MinioClient.ParseError(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 602
   at Minio.MinioClient.<>c.<.ctor>b__166_0(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 84
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 813
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 580
   at Minio.MinioClient.removeObjectsAsync(RemoveObjectsArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/Helper/OperationsHelper.cs:line 109
   at Minio.MinioClient.callRemoveObjects(RemoveObjectsArgs args, List`1 objNames, List`1 fullErrorsList, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/Helper/OperationsHelper.cs:line 146
   at Minio.MinioClient.removeObjectsHelper(RemoveObjectsArgs args, List`1 fullErrorsList, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/Helper/OperationsHelper.cs:line 224
   at Minio.MinioClient.RemoveObjectsAsync(RemoveObjectsArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 381
   at Minio.Functional.Tests.FunctionalTest.ListObjects_Test6(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 2955
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 144
```
This is a time-out issue, and it is understandable we cannot guess how long it is going to take to get a response from different servers, but we should have try/catch blocks encapsulating these tests and not let them fail without cleanup. There is a left over  bucket and all of its content on the GCS as garbage.

2021-05-10 11:23 UTC, ebozduman requested changes
We know that `ACCESS_KEY` and `SECRET_KEY` env vars are deprecated and will be replaced by `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars.
However, `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars are ignored and functional tests fail without `ACCESS_KEY` and `SECRET_KEY` env vars defined.
```
Unhandled Exception: Minio.Exceptions.MinioException: MinIO API responded with message=User Access Credentials not initialized.
   at Minio.MinioClient.Build() in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/DataModel/MinioClientBuilder.cs:line 157
   at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 60

```

2021-05-10 11:43 UTC, ebozduman requested changes
Functional tests running against `NAS` gateway, failed after hitting a "Not implemented" error, which we normally ignore. So, we should have continued with the next test.
```
{"name":"minio-dotnet : BucketTagsAsync_Test1","function":"Task SetBucketTagsAsync(SetBucketTagsArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnetbxi5362idj3gajv"},"duration":51,"status":"PASS"}
{"name":"minio-dotnet : BucketTagsAsync_Test1","function":"Task<Tagging> GetBucketTagsAsync(GetBucketTagsArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnetbxi5362idj3gajv"},"duration":1674,"status":"NA","alert":"A header you provided implies functionality that is not implemented","message":"System.NotImplementedException: A header you provided implies functionality that is not implemented\n   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 763\n   at Minio.MinioClient.ParseError(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 606\n   at Minio.MinioClient.<>c.<.ctor>b__166_0(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 84\n   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 813\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 580\n   at Minio.MinioClient.GetBucketTagsAsync(GetBucketTagsArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 407\n   at Minio.Functional.Tests.FunctionalTest.BucketTagsAsync_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 4398"}
{"name":"minio-dotnet : ObjectTagsAsync_Test1","function":"Task SetObjectTagsAsync(SetObjectTagsArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnet91e31mxy80v8ljo","objectName":"miniodotnetcohugnvqj8"},"duration":29,"status":"PASS"}
```
There are still 11 tests to go.

2021-05-10 19:58 UTC, BigUstad commented
> We know that `ACCESS_KEY` and `SECRET_KEY` env vars are deprecated and will be replaced by `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars.
> However, `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars are ignored and functional tests fail without `ACCESS_KEY` and `SECRET_KEY` env vars defined.
> 
> ```
> Unhandled Exception: Minio.Exceptions.MinioException: MinIO API responded with message=User Access Credentials not initialized.
>    at Minio.MinioClient.Build() in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/DataModel/MinioClientBuilder.cs:line 157
>    at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 60
> ```

minio-dotnet needs either the access key/secret key pair to be initialized or a credentials provider be initialized. If not, this error is thrown.

2021-05-11 20:37 UTC, ebozduman requested changes
I still hit the same issue with NAS gateway:
```
{"name":"minio-dotnet : BucketLifecycleAsync_Test1","function":"Task RemoveBucketLifecycleAsync(RemoveBucketLifecycleArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnetxr5xcw2se24qjz5"},"duration":60,"status":"NA","alert":"A header you provided implies functionality that is not implemented","message":"System.NotImplementedException: A header you provided implies functionality that is not implemented\n   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 763\n   at Minio.MinioClient.ParseError(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 606\n   at Minio.MinioClient.<>c.<.ctor>b__166_0(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 84\n   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 813\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 580\n   at Minio.MinioClient.GetBucketLifecycleAsync(GetBucketLifecycleArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 553\n   at Minio.Functional.Tests.FunctionalTest.BucketLifecycleAsync_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 5123"}
```

2021-05-11 23:49 UTC, BigUstad commented
> I still hit the same issue with NAS gateway:
> 
> ```
> {"name":"minio-dotnet : BucketLifecycleAsync_Test1","function":"Task RemoveBucketLifecycleAsync(RemoveBucketLifecycleArgs args, CancellationToken cancellationToken = default(CancellationToken))","args":{"bucketName":"miniodotnetxr5xcw2se24qjz5"},"duration":60,"status":"NA","alert":"A header you provided implies functionality that is not implemented","message":"System.NotImplementedException: A header you provided implies functionality that is not implemented\n   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 763\n   at Minio.MinioClient.ParseError(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 606\n   at Minio.MinioClient.<>c.<.ctor>b__166_0(IRestResponse response) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 84\n   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 813\n   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/MinioClient.cs:line 580\n   at Minio.MinioClient.GetBucketLifecycleAsync(GetBucketLifecycleArgs args, CancellationToken cancellationToken) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 553\n   at Minio.Functional.Tests.FunctionalTest.BucketLifecycleAsync_Test1(MinioClient minio) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/FunctionalTest.cs:line 5123"}
> ```
> 
> This test is the 57th test out of 66 total.

Without https connection to server & without KMS setup, this is the last testcase to be executed.

2021-05-12 08:25 UTC, ebozduman commented
> > We know that `ACCESS_KEY` and `SECRET_KEY` env vars are deprecated and will be replaced by `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars.
> > However, `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars are ignored and functional tests fail without `ACCESS_KEY` and `SECRET_KEY` env vars defined.
> > ```
> > Unhandled Exception: Minio.Exceptions.MinioException: MinIO API responded with message=User Access Credentials not initialized.
> >    at Minio.MinioClient.Build() in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/DataModel/MinioClientBuilder.cs:line 157
> >    at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 60
> > ```
> 
> minio-dotnet needs either the access key/secret key pair to be initialized or a credentials provider be initialized. If not, this error is thrown.

That is correct. But what I meant was our code **should** accept `"MINIO_ROOT_USER"` env var for access key, and `"MINIO_ROOT_PASSWORD"` env var as the secret key. 
The other pair, `"ACCEPT_KEY"` and `"SECRET_KEY"` are deprecated. We accept them with a warning message telling the customer they are deprecated and `"MINIO_ROOT_USER"` and `"MINIO_ROOT_PASSWORD"` env vars should be used instead.

2021-05-12 16:22 UTC, BigUstad commented
> > > We know that `ACCESS_KEY` and `SECRET_KEY` env vars are deprecated and will be replaced by `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars.
> > > However, `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars are ignored and functional tests fail without `ACCESS_KEY` and `SECRET_KEY` env vars defined.
> > > ```
> > > Unhandled Exception: Minio.Exceptions.MinioException: MinIO API responded with message=User Access Credentials not initialized.
> > >    at Minio.MinioClient.Build() in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/DataModel/MinioClientBuilder.cs:line 157
> > >    at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 60
> > > ```
> > 
> > 
> > minio-dotnet needs either the access key/secret key pair to be initialized or a credentials provider be initialized. If not, this error is thrown.
> 
> That is correct. But what I meant was our code **should** accept `"MINIO_ROOT_USER"` env var for access key, and `"MINIO_ROOT_PASSWORD"` env var as the secret key.
> The other pair, `"ACCEPT_KEY"` and `"SECRET_KEY"` are deprecated. We accept them with a warning message telling the customer they are deprecated and `"MINIO_ROOT_USER"` and `"MINIO_ROOT_PASSWORD"` env vars should be used instead.

This is a good suggestion, but I'd like to keep this PR confined to changes related to Functional tests. Although, it has diverged only a little bit from that.
 Please file an issue to keep track of this suggestion/enhancement.

2021-05-12 16:25 UTC, ebozduman approved these changes
LGTM

2021-05-12 20:15 UTC, kannappanr commented
> > > > We know that `ACCESS_KEY` and `SECRET_KEY` env vars are deprecated and will be replaced by `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars.
> > > > However, `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` env vars are ignored and functional tests fail without `ACCESS_KEY` and `SECRET_KEY` env vars defined.
> > > > ```
> > > > Unhandled Exception: Minio.Exceptions.MinioException: MinIO API responded with message=User Access Credentials not initialized.
> > > >    at Minio.MinioClient.Build() in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio/DataModel/MinioClientBuilder.cs:line 157
> > > >    at Minio.Functional.Tests.Program.Main(String[] args) in /home/ersan/work/src/github.com/minio/minio-dotnet/Minio.Functional.Tests/Program.cs:line 60
> > > > ```
> > > 
> > > 
> > > minio-dotnet needs either the access key/secret key pair to be initialized or a credentials provider be initialized. If not, this error is thrown.
> > 
> > 
> > That is correct. But what I meant was our code **should** accept `"MINIO_ROOT_USER"` env var for access key, and `"MINIO_ROOT_PASSWORD"` env var as the secret key.
> > The other pair, `"ACCEPT_KEY"` and `"SECRET_KEY"` are deprecated. We accept them with a warning message telling the customer they are deprecated and `"MINIO_ROOT_USER"` and `"MINIO_ROOT_PASSWORD"` env vars should be used instead.
> 
> This is a good suggestion, but I'd like to keep this PR confined to changes related to Functional tests. Although, it has diverged only a little bit from that.
> Please file an issue to keep track of this suggestion/enhancement.

This is not a correct suggestion. This is a client side SDK, which does not talk to MinIO alone and we do not require ROOT credentials to talk to a MinIO or any other compatible S3 object storage. Any access key/secret key pair is enough as long as it has the required permissions to complete the functional test

2021-05-12 20:18 UTC, kannappanr commented on Minio.Functional.Tests/Program.cs
> +
```suggestion
```

2021-05-12 20:19 UTC, kannappanr commented on Minio.Functional.Tests/Program.cs
> +
```suggestion
```

2021-05-12 21:14 UTC, BigUstad commented on Minio.Functional.Tests/Program.cs
> +
Changed.

2021-05-13 18:54 UTC, kannappanr approved these changes
LGTM

2021-05-14 01:09 UTC, merged