Fix for issue during setting .WithLifecycleConfiguration (#656)
minio/minio-dotnet pull request #722
Opened 2022-12-05 09:05 UTC by MarDipp

Fixes issue [Error during setting .WithLifecycleConfiguration #656](https://github.com/minio/minio-dotnet/issues/656).

The XML node NoncurrentVersionExpiration was empty because internal properties are not serialized.

2022-12-11 20:20 UTC, harshavardhana approved these changes

2022-12-13 23:25 UTC, ebozduman commented
Reviewing...

2022-12-14 06:25 UTC, ebozduman requested changes
I ran with @peterczabanski 's configuration given in the issue tobe fixed, #656, and `SetBucketLifecycleAsync` api still fails the same way with the same error message.
Your fix looks good, but it seems like the fix needs more changes.

One thing I noticed is; minio-go has 2 properties for `NoncurrentVersionExpiration`
```
<NoncurrentVersionExpiration>     
            <NewerNoncurrentVersions>5</NewerNoncurrentVersions>
            <NoncurrentDays>365</NoncurrentDays>    
</NoncurrentVersionExpiration> 
```
i.e `NewerNoncurrentVersions` is missing.

2022-12-15 12:55 UTC, MarDipp commented
> I ran with @peterczabanski 's configuration given in the issue tobe fixed, #656, and `SetBucketLifecycleAsync` api still fails the same way with the same error message. Your fix looks good, but it seems like the fix needs more changes.
> 
> One thing I noticed is; minio-go has 2 properties for `NoncurrentVersionExpiration`
> 
> ```
> <NoncurrentVersionExpiration>     
>             <NewerNoncurrentVersions>5</NewerNoncurrentVersions>
>             <NoncurrentDays>365</NoncurrentDays>    
> </NoncurrentVersionExpiration> 
> ```
> 
> i.e `NewerNoncurrentVersions` is missing.

The remaining problem with @peterczabanski 's configuration is the part `Filter = null`. [The Filter must not be empty](https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html#intro-lifecycle-rules-filter). To apply the rule to all files an empty prefix can be used: `Filter = new RuleFilter() { Prefix = String.Empty }`

This configuration will work:
`SetBucketLifecycleArgs args = new SetBucketLifecycleArgs() .WithBucket(bucketName) .WithLifecycleConfiguration( new LifecycleConfiguration(new List<LifecycleRule>(new[] { new LifecycleRule { AbortIncompleteMultipartUploadObject = null, ID = "Delete imagines after 31 days", Expiration = null, TransitionObject = null, Filter = new RuleFilter() { Prefix = String.Empty }, NoncurrentVersionExpirationObject = new NoncurrentVersionExpiration(31), NoncurrentVersionTransitionObject = null, Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED } })));`

I'm not sure how this can be fixed. Perhaps an error message can be helpful.

2022-12-19 10:44 UTC, ebozduman commented
@MarDipp ,

> This configuration will work:
SetBucketLifecycleArgs args = new SetBucketLifecycleArgs() .WithBucket(bucketName) .WithLifecycleConfiguration( new LifecycleConfiguration(new List<LifecycleRule>(new[] { new LifecycleRule { AbortIncompleteMultipartUploadObject = null, ID = "Delete imagines after 31 days", Expiration = null, TransitionObject = null, Filter = new RuleFilter() { Prefix = String.Empty }, NoncurrentVersionExpirationObject = new NoncurrentVersionExpiration(31), NoncurrentVersionTransitionObject = null, Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED } })));

Yes. This configuration works.
But we have to fix the `null` value issue for the `Filter` tag. Otherwise, it needs to be documented and it sounds pretty bad to me.

We also need to add the missing `NewerNoncurrentVersions` tag in `NoncurrentVersionExpiration`.

2022-12-19 12:46 UTC, MarDipp commented
> ...
> Yes. This configuration works. But we have to fix the `null` value issue for the `Filter` tag. Otherwise, it needs to be documented and it sounds pretty bad to me.
> 
> We also need to add the missing `NewerNoncurrentVersions` tag in `NoncurrentVersionExpiration`.

I added the property `NewerNoncurrentVersions` like in minio-go.
Additionally it is ensured that the filter is never null. Now @peterczabanski 's configuration works without change.

2022-12-19 14:08 UTC, ebozduman requested changes
I think there is one last issue:

`NoncurrentVersionExpirationObject` has become a mandatory tag and it has to be defined.
Try it with a `null` value and with no `NoncurrentVersionExpirationObject` definition in your Rule.

2022-12-19 14:59 UTC, MarDipp commented
> I think there is one last issue:
> 
> `NoncurrentVersionExpirationObject` has become a mandatory tag and it has to be defined. Try it with a `null` value and with no `NoncurrentVersionExpirationObject` definition in your Rule.

Have you added an other condition?

I don´t think `NoncurrentVersionExpirationObject` is mandatory. But you need either `Expiration`, `TransitionObject`, `NoncurrentVersionExpirationObject` or `NoncurrentVersionTransitionObject` filled. If all of these objects are missing, an XML error is thrown. [Here is the code of the Rule Validation](https://github.com/minio/minio/blob/6511021fbe65148145390894a34143fee3c053f6/internal/bucket/lifecycle/rule.go#L161)

This configuration has no `NoncurrentVersionExpirationObject`, but works anyway: 
`SetBucketLifecycleArgs setPolicyArgs = new SetBucketLifecycleArgs().WithBucket(bucketName).WithLifecycleConfiguration(new LifecycleConfiguration(new List<LifecycleRule>(new[] { new LifecycleRule { AbortIncompleteMultipartUploadObject = null, ID = "Test", Expiration = new Expiration(DateTime.UtcNow.AddYears(10)), TransitionObject = null, Filter = null, NoncurrentVersionExpirationObject = null, NoncurrentVersionTransitionObject = null, Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED } })));`

2022-12-20 04:28 UTC, ebozduman commented
I see. At this point in the code, there is only one required tag, `"Status"` and the following is one of the minimum configs:
```
LifecycleConfiguration lfc = new LifecycleConfiguration(
    new List<LifecycleRule>(new[]
    { new LifecycleRule
        { 
            NoncurrentVersionExpirationObject = new NoncurrentVersionExpiration(31, 5), 
Glacier Flexible Retrieval"), 
            Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED
        }
    }
));
```

while the following config fails:
```
LifecycleConfiguration lfc = new LifecycleConfiguration(
    new List<LifecycleRule>(new[]
    { new LifecycleRule
        { 
            Status = LifecycleRule.LIFECYCLE_RULE_STATUS_ENABLED
        }
    }
));

I guess, at least one of the tags, either transitions or expirations, needs to be provided with values.

So, I guess we can stop here.

LGTM

2022-12-20 04:28 UTC, ebozduman approved these changes

2022-12-20 17:09 UTC, merged