Next fixes
minio/minio-dotnet pull request #779
Opened 2023-05-09 12:55 UTC by martijn00

@ebozduman

2023-05-10 10:43 UTC, ebozduman requested changes

2023-05-10 10:43 UTC, ebozduman commented on Minio/Credentials/MinioEnvironmentProvider.cs
> +        var credentials = new AccessCredentials(Environment.GetEnvironmentVariable("MINIO_ACCESS_KEY"),
`MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` are deprecated.
The newly coming env vars are `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD`.
However, we still honor the deprecated ones if the new env vars are not defined.

2023-05-10 16:20 UTC, ebozduman approved these changes
LGTM

2023-05-10 18:52 UTC, martijn00 commented
@ebozduman I don't know why the test fails. Locally this test passes. Can you try run it again?

2023-05-11 09:08 UTC, martijn00 commented
@ebozduman I've done a rebase to include the parallel tests. Can you run it again?

2023-05-11 10:32 UTC, ebozduman commented
I get the same result; just cannot reproduce the failure reported during build tests on the windows side.
I'll dig in more.

2023-05-15 11:21 UTC, martijn00 commented
@ebozduman any news?

2023-05-22 01:31 UTC, merged