parallel run fixes and lint changes
minio/minio-dotnet pull request #809
Opened 2023-07-27 11:40 UTC by ebozduman

Fix for sporadic functional tests/ build test sporadic failures introduced after parallel run change.
Some a bit of lint changes are also included.

2023-07-28 10:19 UTC, martijn00 requested changes
Looks good to me, but the new range syntax is not available in netstandard

2023-07-28 10:19 UTC, martijn00 commented on Minio.Functional.Tests/Program.cs
> +                port = int.Parse(endPoint.AsSpan(posColon + 1, endPoint.Length - posColon - 1), NumberStyles.Integer,
This is not available in netstandard2.0

2023-07-28 10:19 UTC, martijn00 commented on Minio.Functional.Tests/Program.cs
> +                endPoint = endPoint[..posColon];
This is not available in netstandard2.0

2023-07-28 10:19 UTC, martijn00 commented on Minio.Functional.Tests/FunctionalTest.cs
> +                        var trimmedFront = receivedJson[len..];
This is not available in netstandard2.0

2023-07-28 10:31 UTC, martijn00 commented
@ebozduman would be good to get this merged asap so i can rebase my PR and the other 2 PR's can too

2023-08-01 10:32 UTC, ebozduman commented
@martijn00

I agree, but there are still some failures during build/functional tests. I think we need the flag to turn on/off parallel lrun flag, your suggestion, to be able to let those PRs pending to be merged just because the build tests fail when run in parallel, unrelated to the fixes/changes those PRs bring in.

2023-08-09 05:32 UTC, ebozduman commented
I reviewed the changes one more time and I think I need to revisit this one, rebase and resolve the conflicts and definitely merge at least 2, likely medium priority changes in, if not all.

2023-08-23 23:48 UTC, ebozduman commented
There is no need for this PR anymore.
Closing...

2023-08-23 23:48 UTC, closed without merging