Warnings8
minio/minio-dotnet pull request #848
Opened 2023-08-24 16:08 UTC by martijn00

@ebozduman can you run and check this PR?

2023-08-25 08:06 UTC, martijn00 commented
@ebozduman it seems to run! Can you merge?

2023-08-26 02:05 UTC, ebozduman requested changes

2023-08-26 09:16 UTC, ebozduman commented
@martijn00 

The build failure is not because of the latest lint changes.
The failing tests are `GetObjectS3Zip_Test1`, `BucketLifecycleAsync_Test1.1`, and `GetObject_AsyncCallback_Test1`. So, they are totally unrelated.
I also confirmed it by undoing the last check-in, the lint changes, and the same 3 functional tests still fail the same way. This issue is one I am currently working on, PR [#844](https://github.com/minio/minio-dotnet/pull/84). 
PR #844 resolves the duration calculation issue, but there is another failure revealed after that and I am looking into it.
So, as soon as PR #844 is merged, this one can be rebased and merged.

2023-08-27 00:57 UTC, ebozduman approved these changes

2023-08-27 00:58 UTC, merged